### ISSUE TITLE
How to generate more datasets mentioned in configs?

### ISSUE THREAD

**Issue by zhangyxrepo** [CurryTang/TSGFM#5]
Hi @CurryTang and other authors, thanks for sharing your work. I'd like to ask about generating additional datasets referenced in `data_config.yaml`.

I've noticed several entries corresponding to unseen graphs which are not included in `AVAILABLE_DATA` in `gen_data.py`, such as:

```yaml
arxiv23_low: &arxiv23_low
  <<: *E2E-node
  dataset_name: arxiv23
  dataset_splitter: LowRateSplitter
  process_label_func: process_pth_label
  num_classes: 40

bookchild20: &bookchild20
  <<: *E2E-node
  dataset_name: bookchild
  dataset_splitter: TwentySplitter
  process_label_func: process_pth_label
  num_classes: 24

elecomp20: &elecomp20
  <<: *E2E-node
  dataset_name: elecomp
  dataset_splitter: TwentySplitter
  process_label_func: process_pth_label
  num_classes: 10
```
However, I couldn't locate corresponding generation methods for these datasets in the repository. Could you kindly provide guidance on any available scripts/instructions for creating them? Whether these datasets require separate generation procedures? And if they are derivatives of existing datasets, what preprocessing steps are needed? And I also want to know if you have evaluated methods on them and what the results were?

Thanks in advance.
